let firstName = "John"; console.log(typeof firstName)
let lastName = "Maguayer";  console.log(typeof lastName)
let contry = "USA";  console.log(typeof contry)
let city = "New York";  console.log(typeof city)
let Age = 39;  console.log(typeof Age)
let isMarried = "Yes";  console.log(typeof isMarried)
let year = 1984;  console.log(typeof year)
